name: MQTT 每5分钟仿真冷藏温度（整数纯数字）

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  mqtt-publisher:
    runs-on: ubuntu-latest
    steps:
      - name: 发布模拟温度（纯数字）
        run: |
          pip install paho-mqtt
          echo "import paho.mqtt.publish as publish" > publish.py
          echo "import random" >> publish.py
          echo "value = random.choice(['2', '3'])" >> publish.py
          echo "publish.single(" >> publish.py
          echo "    topic='/fridgeguard/test/message'," >> publish.py
          echo "    payload=str(value)," >> publish.py
          echo "    hostname='test.mosquitto.org'," >> publish.py
          echo "    port=1883," >> publish.py
          echo "    retain=True" >> publish.py
          echo ")" >> publish.py
          python3 publish.py
