name: MQTT 每10分钟发布 2 或 3（强保留）

on:
  schedule:
    - cron: '*/10 * * * *'
    - cron: '0 9 * * *'
  workflow_dispatch:
jobs:
  mqtt-publisher:
    runs-on: ubuntu-latest
    steps:
      - name: 发布带 retained 的消息（确保生效）
        run: |
          pip install paho-mqtt
          echo "import paho.mqtt.client as mqtt" > publish.py
          echo "import random" >> publish.py
          echo "broker = 'test.mosquitto.org'" >> publish.py
          echo "port = 1883" >> publish.py
          echo "topic = '/fridgeguard/test/message'" >> publish.py
          echo "payload = random.choice(['2', '3'])" >> publish.py
          echo "client = mqtt.Client()" >> publish.py
          echo "client.connect(broker, port, 60)" >> publish.py
          echo "result = client.publish(topic, payload, retain=True)" >> publish.py
          echo "result.wait_for_publish()" >> publish.py
          echo "client.disconnect()" >> publish.py
          python3 publish.py
