name: MQTT 每30分钟仿真冷藏温度（整数纯数字）

on:
  schedule:
    - cron: '*/30 * * * *'  # 每30分钟运行一次
  workflow_dispatch:

jobs:
  mqtt-publisher:
    runs-on: ubuntu-latest
    timeout-minutes: 2  # 防止任务卡住
    steps:
      - name: 发布模拟温度（使用稳定 MQTT 客户端）
        run: |
          pip install paho-mqtt
          echo "import paho.mqtt.client as mqtt" > publish.py
          echo "import random" >> publish.py
          echo "broker = 'test.mosquitto.org'" >> publish.py
          echo "port = 1883" >> publish.py
          echo "topic = '/fridgeguard/test/message'" >> publish.py
          echo "payload = random.choice(['2', '3'])" >> publish.py
          echo "client = mqtt.Client(protocol=mqtt.MQTTv311)" >> publish.py
          echo "client.connect(broker, port, 60)" >> publish.py
          echo "result = client.publish(topic, payload, retain=True)" >> publish.py
          echo "result.wait_for_publish()" >> publish.py
          echo "client.disconnect()" >> publish.py
          python3 publish.py
