name: MQTT 每分钟自动发布消息

on:
  schedule:
    - cron: '*/5 * * * *'   # 每1分钟运行一次
  workflow_dispatch:

jobs:
  mqtt-publisher:
    runs-on: ubuntu-latest
    steps:
      - name: 安装 Python MQTT 库并发布消息
        run: |
          pip install paho-mqtt
          echo "import paho.mqtt.publish as publish" > publish.py
          echo "publish.single(" >> publish.py
          echo "    topic='/fridgeguard/test/message'," >> publish.py
          echo "    payload='2'," >> publish.py
          echo "    hostname='test.mosquitto.org'," >> publish.py
          echo "    port=1883," >> publish.py
          echo "    retain=True" >> publish.py
          echo ")" >> publish.py
          python3 publish.py
